In [1]:
import pandas as pd
import numpy as np
import pandas_profiling

In [4]:
ind = [('AP', 2000), ('AP', 2010),
         ('KA', 2000), ('KA', 2010),
         ('TN', 2000), ('TN', 2010),
      ('TS',2000),('TS',2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561,
              2504789,5689752]

In [5]:
pop = pd.Series(populations,index=ind)

In [6]:
pop

(AP, 2000)    33871648
(AP, 2010)    37253956
(KA, 2000)    18976457
(KA, 2010)    19378102
(TN, 2000)    20851820
(TN, 2010)    25145561
(TS, 2000)     2504789
(TS, 2010)     5689752
dtype: int64

In [7]:
pop[('AP', 2000)]

33871648

In [8]:
pop[0]

33871648

In [9]:
pop[0:5]

(AP, 2000)    33871648
(AP, 2010)    37253956
(KA, 2000)    18976457
(KA, 2010)    19378102
(TN, 2000)    20851820
dtype: int64

In [10]:
pop[('AP',2010):('TS',2000)]

(AP, 2010)    37253956
(KA, 2000)    18976457
(KA, 2010)    19378102
(TN, 2000)    20851820
(TN, 2010)    25145561
(TS, 2000)     2504789
dtype: int64

In [11]:
pop.index

Index([('AP', 2000), ('AP', 2010), ('KA', 2000), ('KA', 2010), ('TN', 2000),
       ('TN', 2010), ('TS', 2000), ('TS', 2010)],
      dtype='object')

In [12]:
pop[[i for i in pop.index if i[1] == 2010]]

(AP, 2010)    37253956
(KA, 2010)    19378102
(TN, 2010)    25145561
(TS, 2010)     5689752
dtype: int64

In [14]:
for i in pop.index:
    if i[1] == 2010:
        print(i,pop[i])

('AP', 2010) 37253956
('KA', 2010) 19378102
('TN', 2010) 25145561
('TS', 2010) 5689752


In [15]:
index = pd.MultiIndex.from_tuples(ind)

In [16]:
index

MultiIndex([('AP', 2000),
            ('AP', 2010),
            ('KA', 2000),
            ('KA', 2010),
            ('TN', 2000),
            ('TN', 2010),
            ('TS', 2000),
            ('TS', 2010)],
           )

In [17]:
pop = pop.reindex(index)

In [18]:
pop

AP  2000    33871648
    2010    37253956
KA  2000    18976457
    2010    19378102
TN  2000    20851820
    2010    25145561
TS  2000     2504789
    2010     5689752
dtype: int64

In [19]:
pop['AP']

2000    33871648
2010    37253956
dtype: int64

In [21]:
pop['TS']

2000    1012
2010    1013
dtype: int64

In [20]:
pop[2]

18976457

In [21]:
pop[0:4]

AP  2000    33871648
    2010    37253956
KA  2000    18976457
    2010    19378102
dtype: int64

In [23]:
pop[0::2]

AP  2000    33871648
KA  2000    18976457
TN  2000    20851820
TS  2000     2504789
dtype: int64

In [24]:
pop[::-1]

TS  2010     5689752
    2000     2504789
TN  2010    25145561
    2000    20851820
KA  2010    19378102
    2000    18976457
AP  2010    37253956
    2000    33871648
dtype: int64

In [25]:
pop[:,2010]

AP    37253956
KA    19378102
TN    25145561
TS     5689752
dtype: int64

In [26]:
pop.ndim

1

In [27]:
pop

AP  2000    33871648
    2010    37253956
KA  2000    18976457
    2010    19378102
TN  2000    20851820
    2010    25145561
TS  2000     2504789
    2010     5689752
dtype: int64

In [28]:
pop_df = pop.unstack()
pop_df

2000      2010
AP  33871648  37253956
KA  18976457  19378102
TN  20851820  25145561
TS   2504789   5689752

In [29]:
pop_df.ndim

2

In [30]:
Se = pop_df.stack()

In [31]:
Se

AP  2000    33871648
    2010    37253956
KA  2000    18976457
    2010    19378102
TN  2000    20851820
    2010    25145561
TS  2000     2504789
    2010     5689752
dtype: int64

In [33]:
Se.ndim

1

In [34]:
pop_df = pd.DataFrame({'Total' :pop,
                      'under18':[96782,90765,
                                12345,907865,
                                90785,907432,
                                90875,99764]})
pop_df

Total  under18
AP 2000   12345    96782
   2010   34567    90765
KA 20000  45678    12345
   2010   91234   907865
TN 2000    6785    90785
   2010    1011   907432
TS 2000    1012    90875
   2010    1013    99764

In [36]:
f_u18 = pop_df['under18']/pop_df['Total']
f_u18.unstack()

2000        2010      20000
AP   7.839773    2.625770       NaN
KA        NaN    9.950950  0.270261
TN  13.380251  897.558853       NaN
TS  89.797431   98.483712       NaN

In [37]:
df = pd.DataFrame(np.random.rand(4, 2),
                 index=[['a','b','c','d'],[1,2,3,4]],
                 columns =['data1','data2'])

In [38]:
df

data1     data2
a 1  0.422807  0.664334
b 2  0.272868  0.608195
c 3  0.939147  0.312872
d 4  0.313767  0.244502

In [39]:
data = {('AP',2000):33756,('AP',2010):11234,('KA',20000):5678,
      ('KA',2010):12345,('TN',2000):78790,
      ('TN',2010):34467,('TS',2000):8877,
      ('TS',2010):12333}

In [40]:
data

{('AP', 2000): 33756,
 ('AP', 2010): 11234,
 ('KA', 20000): 5678,
 ('KA', 2010): 12345,
 ('TN', 2000): 78790,
 ('TN', 2010): 34467,
 ('TS', 2000): 8877,
 ('TS', 2010): 12333}

In [41]:
pd.Series(data)

AP  2000     33756
    2010     11234
KA  20000     5678
    2010     12345
TN  2000     78790
    2010     34467
TS  2000      8877
    2010     12333
dtype: int64

In [42]:
pop.index.names = ['state', 'year']
pop

state  year 
AP     2000     12345
       2010     34567
KA     20000    45678
       2010     91234
TN     2000      6785
       2010      1011
TS     2000      1012
       2010      1013
dtype: int64

In [46]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2,3]],
                                  names=['year','vist'])
columns = pd.MultiIndex.from_product([['Ram', 'shan','sam'],['BMI','temp','weight']],
                                   names=['names_pas','dis'])

In [49]:
data = np.round(np.random.randn(6,9),2)

In [50]:
data

array([[ 0.78, -0.03, -0.71,  0.51,  0.04, -1.07,  0.09,  0.94, -0.9 ],
       [ 0.55,  0.5 , -1.7 , -0.14,  0.48,  0.45,  0.36,  0.75, -0.07],
       [-1.71,  0.21,  2.06, -0.58, -1.56,  0.86,  0.45,  0.03,  0.23],
       [-1.11,  0.59, -0.15, -0.77,  0.72,  2.77, -0.41,  1.23, -0.93],
       [ 0.66, -0.53, -0.45,  0.74,  0.48,  1.94,  2.86, -0.62, -0.29],
       [-0.44,  0.02,  0.43,  0.96, -0.39, -0.61,  0.92,  1.53, -0.25]])

In [51]:
data[:,::2] *= 10

In [52]:
data

array([[ 7.80e+00, -3.00e-02, -7.10e+00,  5.10e-01,  4.00e-01, -1.07e+00,
         9.00e-01,  9.40e-01, -9.00e+00],
       [ 5.50e+00,  5.00e-01, -1.70e+01, -1.40e-01,  4.80e+00,  4.50e-01,
         3.60e+00,  7.50e-01, -7.00e-01],
       [-1.71e+01,  2.10e-01,  2.06e+01, -5.80e-01, -1.56e+01,  8.60e-01,
         4.50e+00,  3.00e-02,  2.30e+00],
       [-1.11e+01,  5.90e-01, -1.50e+00, -7.70e-01,  7.20e+00,  2.77e+00,
        -4.10e+00,  1.23e+00, -9.30e+00],
       [ 6.60e+00, -5.30e-01, -4.50e+00,  7.40e-01,  4.80e+00,  1.94e+00,
         2.86e+01, -6.20e-01, -2.90e+00],
       [-4.40e+00,  2.00e-02,  4.30e+00,  9.60e-01, -3.90e+00, -6.10e-01,
         9.20e+00,  1.53e+00, -2.50e+00]])

In [53]:
data += 37

In [54]:
data

array([[44.8 , 36.97, 29.9 , 37.51, 37.4 , 35.93, 37.9 , 37.94, 28.  ],
       [42.5 , 37.5 , 20.  , 36.86, 41.8 , 37.45, 40.6 , 37.75, 36.3 ],
       [19.9 , 37.21, 57.6 , 36.42, 21.4 , 37.86, 41.5 , 37.03, 39.3 ],
       [25.9 , 37.59, 35.5 , 36.23, 44.2 , 39.77, 32.9 , 38.23, 27.7 ],
       [43.6 , 36.47, 32.5 , 37.74, 41.8 , 38.94, 65.6 , 36.38, 34.1 ],
       [32.6 , 37.02, 41.3 , 37.96, 33.1 , 36.39, 46.2 , 38.53, 34.5 ]])

In [56]:
health_data = pd.DataFrame(data, index=index, columns=columns)

In [57]:
health_data

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2013 1     44.8  36.97   29.9  37.51  37.4  35.93  37.9  37.94   28.0
     2     42.5  37.50   20.0  36.86  41.8  37.45  40.6  37.75   36.3
     3     19.9  37.21   57.6  36.42  21.4  37.86  41.5  37.03   39.3
2014 1     25.9  37.59   35.5  36.23  44.2  39.77  32.9  38.23   27.7
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1
     3     32.6  37.02   41.3  37.96  33.1  36.39  46.2  38.53   34.5

In [58]:
health_data.to_csv("Health_Data_For_Multiindexing.csv")

In [59]:
health_data

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2013 1     44.8  36.97   29.9  37.51  37.4  35.93  37.9  37.94   28.0
     2     42.5  37.50   20.0  36.86  41.8  37.45  40.6  37.75   36.3
     3     19.9  37.21   57.6  36.42  21.4  37.86  41.5  37.03   39.3
2014 1     25.9  37.59   35.5  36.23  44.2  39.77  32.9  38.23   27.7
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1
     3     32.6  37.02   41.3  37.96  33.1  36.39  46.2  38.53   34.5

In [60]:
health_data['Ram']

dis         BMI   temp  weight
year vist                     
2013 1     44.8  36.97    29.9
     2     42.5  37.50    20.0
     3     19.9  37.21    57.6
2014 1     25.9  37.59    35.5
     2     43.6  36.47    32.5
     3     32.6  37.02    41.3

In [61]:
health_data.iloc[1]

names_pas  dis   
Ram        BMI       42.50
           temp      37.50
           weight    20.00
shan       BMI       36.86
           temp      41.80
           weight    37.45
sam        BMI       40.60
           temp      37.75
           weight    36.30
Name: (2013, 2), dtype: float64

In [62]:
health_data.iloc[1:2]

names_pas   Ram                shan                sam              
dis         BMI  temp weight    BMI  temp weight   BMI   temp weight
year vist                                                           
2013 2     42.5  37.5   20.0  36.86  41.8  37.45  40.6  37.75   36.3

In [63]:
pop['AP',2000]

12345

In [64]:
pop['AP']

year
2000    12345
2010    34567
dtype: int64

In [65]:
pop.loc['AP':'TN']

state  year 
AP     2000     12345
       2010     34567
KA     20000    45678
       2010     91234
TN     2000      6785
       2010      1011
dtype: int64

In [66]:
pop[:,2000]

state
AP    12345
TN     6785
TS     1012
dtype: int64

In [67]:
pop[pop > 220000000]

Series([], dtype: int64)

In [68]:
pop[['AP', 'TN']]

state  year
AP     2000    12345
       2010    34567
TN     2000     6785
       2010     1011
dtype: int64

In [69]:
health_data

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2013 1     44.8  36.97   29.9  37.51  37.4  35.93  37.9  37.94   28.0
     2     42.5  37.50   20.0  36.86  41.8  37.45  40.6  37.75   36.3
     3     19.9  37.21   57.6  36.42  21.4  37.86  41.5  37.03   39.3
2014 1     25.9  37.59   35.5  36.23  44.2  39.77  32.9  38.23   27.7
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1
     3     32.6  37.02   41.3  37.96  33.1  36.39  46.2  38.53   34.5

In [70]:
health_data['Ram']

dis         BMI   temp  weight
year vist                     
2013 1     44.8  36.97    29.9
     2     42.5  37.50    20.0
     3     19.9  37.21    57.6
2014 1     25.9  37.59    35.5
     2     43.6  36.47    32.5
     3     32.6  37.02    41.3

In [71]:
health_data.iloc[:1]

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2013 1     44.8  36.97   29.9  37.51  37.4  35.93  37.9  37.94   28.0

In [72]:
health_data.iloc[3:-1]

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2014 1     25.9  37.59   35.5  36.23  44.2  39.77  32.9  38.23   27.7
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1

In [73]:
health_data.iloc[:3:-1]

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2014 3     32.6  37.02   41.3  37.96  33.1  36.39  46.2  38.53   34.5
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1

In [74]:
health_data.iloc[-3 : :]

names_pas   Ram                 shan                sam              
dis         BMI   temp weight    BMI  temp weight   BMI   temp weight
year vist                                                            
2014 1     25.9  37.59   35.5  36.23  44.2  39.77  32.9  38.23   27.7
     2     43.6  36.47   32.5  37.74  41.8  38.94  65.6  36.38   34.1
     3     32.6  37.02   41.3  37.96  33.1  36.39  46.2  38.53   34.5

In [76]:
health_data.loc[:, ('Ram','temp')]

year  vist
2013  1       36.97
      2       37.50
      3       37.21
2014  1       37.59
      2       36.47
      3       37.02
Name: (Ram, temp), dtype: float64

In [78]:
health_data.loc[:,('Ram')]

dis         BMI   temp  weight
year vist                     
2013 1     44.8  36.97    29.9
     2     42.5  37.50    20.0
     3     19.9  37.21    57.6
2014 1     25.9  37.59    35.5
     2     43.6  36.47    32.5
     3     32.6  37.02    41.3

In [79]:
idx = pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'temp']]

names_pas    Ram  shan    sam
dis         temp  temp   temp
year vist                    
2013 1     36.97  37.4  37.94
2014 1     37.59  44.2  38.23

In [80]:
health_data.loc[idx[2:,2],idx[:,'BMI']]

names_pas   Ram   shan   sam
dis         BMI    BMI   BMI
year vist                   
2013 2     42.5  36.86  40.6
2014 2     43.6  37.74  65.6

In [83]:
index = pd.MultiIndex.from_product([['a', 'c', 'b', 'd'],[1,2]])
data = pd.Series(np.random.rand(8),index=index)
data.index.names = ['char', 'int']
data                    

char  int
a     1      0.566030
      2      0.743235
c     1      0.211226
      2      0.457677
b     1      0.761329
      2      0.088026
d     1      0.134947
      2      0.366134
dtype: float64

In [84]:
data['a':'c']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [85]:
try:
    data['a':'b']
except KeyError as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'


In [86]:
data = data.sort_index()

In [87]:
data

char  int
a     1      0.566030
      2      0.743235
b     1      0.761329
      2      0.088026
c     1      0.211226
      2      0.457677
d     1      0.134947
      2      0.366134
dtype: float64

In [88]:
data['a':'c']

char  int
a     1      0.566030
      2      0.743235
b     1      0.761329
      2      0.088026
c     1      0.211226
      2      0.457677
dtype: float64

In [2]:
pd.__version__

'1.0.3'

In [3]:
np.__version__

'1.18.1'