In [1]:
import numpy as np

In [2]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [3]:
a[0]

0

In [4]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [5]:
a[ : :-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [6]:
for i in a:
    print(i**(1/3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [7]:
def f(x,y):
    return x+y
b = np.fromfunction(f,(5,4),dtype=int)

In [8]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [9]:
b[2,3]

5

In [10]:
b[0:5, 1] 

array([1, 2, 3, 4, 5])

In [11]:
b[ : ,1]

array([1, 2, 3, 4, 5])

In [12]:
b[1:3, : ]

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [13]:
b[-1]

array([4, 5, 6, 7])

In [14]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [15]:
b[-1,-1]

7

In [16]:
b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [17]:
for row in b:
    print(row)

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]


In [18]:
b[-1,-2]

6