In [1]:
import pandas as pd
import numpy as np

In [2]:
rng = np.random.RandomState()
ser = pd.Series(rng.random(10))
print(ser)

0    0.567935
1    0.723956
2    0.898538
3    0.752145
4    0.461239
5    0.384344
6    0.207764
7    0.866040
8    0.694552
9    0.495898
dtype: float64


In [3]:
print(id(rng))

1694538039368


In [4]:
type(ser)

pandas.core.series.Series

In [5]:
df = pd.DataFrame(rng.randint(0, 10, (4, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  9  2  4  3
1  5  0  8  9
2  0  0  3  8
3  6  5  9  9

In [6]:
df.mean(axis = 0)

A    5.00
B    1.75
C    6.00
D    7.25
dtype: float64

In [7]:
df.mean(1)

0    4.50
1    5.50
2    2.75
3    7.25
dtype: float64

In [8]:
df.median(axis = 'rows')

A    5.5
B    1.0
C    6.0
D    8.5
dtype: float64

In [9]:
np.exp(ser)

0    1.764619
1    2.062576
2    2.456010
3    2.121546
4    1.586038
5    1.468651
6    1.230923
7    2.377478
8    2.002812
9    1.641973
dtype: float64

In [10]:
np.sin(df * np.pi / 4)

A         B             C             D
0  0.707107  1.000000  1.224647e-16  7.071068e-01
1 -0.707107  0.000000 -2.449294e-16  7.071068e-01
2  0.000000  0.000000  7.071068e-01 -2.449294e-16
3 -1.000000 -0.707107  7.071068e-01  7.071068e-01

In [11]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')
area

Alaska        1723337
Texas          695662
California     423967
Name: area, dtype: int64

In [12]:
population

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64

In [13]:
print(population)

California    38332521
Texas         26448193
New York      19651127
Name: population, dtype: int64


In [14]:
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [15]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [16]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A

0    2
1    4
2    6
dtype: int64

In [17]:
B

1    1
2    3
3    5
dtype: int64

In [18]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [19]:
A*B

0     NaN
1     4.0
2    18.0
3     NaN
dtype: float64

In [20]:
print(A)
print(B)

0    2
1    4
2    6
dtype: int64
1    1
2    3
3    5
dtype: int64


In [21]:
fill = np.mean(A).astype(int)
fill

4

In [22]:
A.add(B, fill_value=fill)

0    6.0
1    5.0
2    9.0
3    9.0
dtype: float64

In [23]:
A = pd.DataFrame(rng.randint(0, 20, (3, 5)),
                 columns=list('ABCDE'))
A

A   B   C   D   E
0  13   9  16  11   2
1   7   7  19   7  15
2  13  16  15   6   9

In [24]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns=list('BAC'))
B

B  A  C
0  4  9  6
1  0  6  9
2  1  6  0

In [25]:
A + B

A   B   C   D   E
0  22  13  22 NaN NaN
1  13   7  28 NaN NaN
2  19  17  15 NaN NaN

In [26]:
A*B

A   B    C   D   E
0  117  36   96 NaN NaN
1   42   0  171 NaN NaN
2   78  16    0 NaN NaN

In [27]:
Data = A.stack()
Data

0  A    13
   B     9
   C    16
   D    11
   E     2
1  A     7
   B     7
   C    19
   D     7
   E    15
2  A    13
   B    16
   C    15
   D     6
   E     9
dtype: int32

In [28]:
Data.sum()/len(Data)

11.0

In [29]:
fill = A.stack().mean()
fill

11.0

In [30]:
A.add(B, fill_value=fill,axis=0)

A   B   C     D     E
0  22  13  22  22.0  13.0
1  13   7  28  18.0  26.0
2  19  17  15  17.0  20.0

In [31]:
A.add(B, fill_value=fill,axis='rows')

A   B   C     D     E
0  22  13  22  22.0  13.0
1  13   7  28  18.0  26.0
2  19  17  15  17.0  20.0

In [32]:
A = rng.randint(10, size=(3, 4))
A

array([[4, 9, 7, 4],
       [6, 6, 2, 1],
       [2, 0, 8, 1]])

In [33]:
A[0]

array([4, 9, 7, 4])

In [34]:
A - A[0]

array([[ 0,  0,  0,  0],
       [ 2, -3, -5, -3],
       [-2, -9,  1, -3]])

In [35]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  4  9  7  4
1  6  6  2  1
2  2  0  8  1

In [36]:
df['Q'][0]

4

In [37]:
df.iloc[0]

Q    4
R    9
S    7
T    4
Name: 0, dtype: int32

In [38]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1  2 -3 -5 -3
2 -2 -9  1 -3

In [39]:
df['R']

0    9
1    6
2    0
Name: R, dtype: int32

In [40]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -2 -5
1  0  0 -4 -5
2  2  0  8  1

In [41]:
df.subtract(df['R'], axis=1)

Q   R   S   T   0   1   2
0 NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN

In [42]:
df

Q  R  S  T
0  4  9  7  4
1  6  6  2  1
2  2  0  8  1

In [43]:
halfrow = df.iloc[1, ::2]
halfrow

Q    6
S    2
Name: 1, dtype: int32

In [44]:
df - halfrow

Q   R    S   T
0 -2.0 NaN  5.0 NaN
1  0.0 NaN  0.0 NaN
2 -4.0 NaN  6.0 NaN