In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [3]:
vals1.dtype

dtype('O')

In [4]:
vals1.dtype.name

'object'

In [5]:
V = np.arange(12).reshape(3,4)
V

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
V.dtype

dtype('int32')

In [7]:
V[0][3]=None
V

TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

In [8]:
%timeit  # it is Used in Jupyter to Check the time take Process for this Current Cell
try:
    a = 'H2'
    print(int(a))
except NameError as ne:
    print(ne)


ValueError: empty body on For

In [9]:
np.arange(1E6)

array([0.00000e+00, 1.00000e+00, 2.00000e+00, ..., 9.99997e+05,
       9.99998e+05, 9.99999e+05])

In [10]:
for dtype in ['object','int','float','complex']:
    print("dtype =", dtype)
    %timeit np.arange(1E3, dtype=dtype).sum()
    print()


dtype = object
221 µs ± 12.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

dtype = int
35.5 µs ± 343 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

dtype = float
38.4 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

dtype = complex
41 µs ± 788 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)



In [11]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [ ]:
vals1.mean()

In [ ]:
vals1+10

In [12]:
vals2 = np.array([1,3, 4,np.nan]) 
vals2.dtype

dtype('float64')

In [13]:
1 + np.nan

nan

In [14]:
0 *  np.nan

nan

In [15]:
vals2.sum(), vals2.min(), vals2.max(),vals2.mean()

(nan, nan, nan, nan)

In [16]:
np.nansum(vals2), np.nanmin(vals2), np.nanmax(vals2),np.nanmean(vals2)

(8.0, 1.0, 4.0, 2.6666666666666665)

In [17]:
pd.Series([1, np.nan, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [18]:
x = pd.Series(range(4), dtype=int)
x

0    0
1    1
2    2
3    3
dtype: int32

In [19]:
x[3] = None
x

0    0.0
1    1.0
2    2.0
3    NaN
dtype: float64

In [20]:
x.add(2)

0    2.0
1    3.0
2    4.0
3    NaN
dtype: float64

In [21]:
np.nan_to_num(x)

array([0., 1., 2., 0.])

In [22]:
np.nanmax(x)

2.0

In [23]:
np.nanmin(x)

0.0

In [24]:
np.nanmean(x),np.nanmedian(x),np.nancumsum(x)

(1.0, 1.0, array([0., 1., 3., 3.]))

In [25]:
x = np.array([10,20,30, np.nan,None])
x

array([10, 20, 30, nan, None], dtype=object)

In [26]:
x.min()

TypeError: '<=' not supported between instances of 'float' and 'NoneType'

In [27]:
x.dtype

dtype('O')

In [28]:
Data = pd.Series([10,20,30, np.nan,None])
Data

0    10.0
1    20.0
2    30.0
3     NaN
4     NaN
dtype: float64

In [29]:
Data.min()

10.0

In [30]:
data = pd.Series([1, np.nan, 10.5, None])
data

0     1.0
1     NaN
2    10.5
3     NaN
dtype: float64

In [31]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [32]:
data.isna()

0    False
1     True
2    False
3     True
dtype: bool

In [33]:
data.notna()

0     True
1    False
2     True
3    False
dtype: bool

In [34]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [35]:
Df = pd.DataFrame(data,columns=['Data'])
Df

Data
0   1.0
1   NaN
2  10.5
3   NaN

In [36]:
Df.isnull()

Data
0  False
1   True
2  False
3   True

In [37]:
Df.isnull().sum()

Data    2
dtype: int64

In [38]:
Df['Age']=np.array([24,23,45,56])
Df

Data  Age
0   1.0   24
1   NaN   23
2  10.5   45
3   NaN   56

In [39]:
Df['Gender'] = pd.Categorical(['M','F','M','F'])

In [40]:
Df

Data  Age Gender
0   1.0   24      M
1   NaN   23      F
2  10.5   45      M
3   NaN   56      F

In [41]:
Df.dtypes

Data       float64
Age          int32
Gender    category
dtype: object

In [42]:
Df.isnull()

Data    Age  Gender
0  False  False   False
1   True  False   False
2  False  False   False
3   True  False   False

In [43]:
Df.isnull().sum()

Data      2
Age       0
Gender    0
dtype: int64

In [44]:
Df.notnull()

Data   Age  Gender
0   True  True    True
1  False  True    True
2   True  True    True
3  False  True    True

In [45]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [46]:
data[data.notnull()]

0     1.0
2    10.5
dtype: float64

In [47]:
Df[Df.notnull()]

Data  Age Gender
0   1.0   24      M
1   NaN   23      F
2  10.5   45      M
3   NaN   56      F

In [48]:
Df[Df['Data'].notnull()]

Data  Age Gender
0   1.0   24      M
2  10.5   45      M

In [49]:
data

0     1.0
1     NaN
2    10.5
3     NaN
dtype: float64

In [50]:
data.dropna()

0     1.0
2    10.5
dtype: float64

In [51]:
data

0     1.0
1     NaN
2    10.5
3     NaN
dtype: float64

In [52]:
data.fillna(value=2)

0     1.0
1     2.0
2    10.5
3     2.0
dtype: float64

In [53]:
data.fillna(value={1:2.5,3:50})

0     1.0
1     2.5
2    10.5
3    50.0
dtype: float64

In [54]:
mean = np.nanmean(data)
print(mean)

5.75


In [55]:
data.fillna(value=mean)

0     1.00
1     5.75
2    10.50
3     5.75
dtype: float64

In [56]:
data

0     1.0
1     NaN
2    10.5
3     NaN
dtype: float64

In [57]:
fill = np.nanmedian(data)
fill

5.75

In [58]:
data.fillna(value=mean)

0     1.00
1     5.75
2    10.50
3     5.75
dtype: float64

In [59]:
df = pd.DataFrame([[1,      np.nan, 2, None],
                   [2,      3,      5, 10  ],
                   [np.nan, 4,      9, 155 ]],columns=['A','B','C','D'])
df

A    B  C      D
0  1.0  NaN  2    NaN
1  2.0  3.0  5   10.0
2  NaN  4.0  9  155.0

In [60]:
df.dropna()

A    B  C     D
1  2.0  3.0  5  10.0

In [61]:
df.dropna(axis=1)

C
0  2
1  5
2  9

In [62]:
df.dropna(axis='columns')

C
0  2
1  5
2  9

In [63]:
df.dropna(axis='rows')

A    B  C     D
1  2.0  3.0  5  10.0

In [64]:
df['D'] = np.nan
df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  9 NaN

In [65]:
df.dropna(axis='columns', how='all')

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  9

In [66]:
df.dropna(axis=1, how='all')

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  9

In [67]:
df.dropna(axis='columns', how='any')

C
0  2
1  5
2  9

In [68]:
df.dropna(axis=0, how='any')

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [69]:
df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  9 NaN

In [70]:
df.dropna(axis='rows', thresh=3)

A    B  C   D
1  2.0  3.0  5 NaN

In [71]:
df.dropna(axis='rows', thresh=2)

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  9 NaN

In [72]:
df.dropna(axis='columns', thresh=3)

C
0  2
1  5
2  9

In [73]:
df.dropna(axis='columns', thresh=2)

A    B  C
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  9

In [74]:
Df = pd.DataFrame({'Int':[10,20,30,np.nan,50,60],
                  'Float':[20.5,10.5,5.5,2.5,6.5,np.nan],
                   'Complex':[np.nan,2j+3,np.nan,23j+2,5j+2,np.nan]
                  })
Df

Int  Float              Complex
0  10.0   20.5                  NaN
1  20.0   10.5   3.000000+2.000000j
2  30.0    5.5                  NaN
3   NaN    2.5  2.000000+23.000000j
4  50.0    6.5   2.000000+5.000000j
5  60.0    NaN                  NaN

In [75]:
Df.isnull()

Int  Float  Complex
0  False  False     True
1  False  False    False
2  False  False     True
3   True  False    False
4  False  False    False
5  False   True     True

In [76]:
Df.isna()

Int  Float  Complex
0  False  False     True
1  False  False    False
2  False  False     True
3   True  False    False
4  False  False    False
5  False   True     True

In [77]:
Df.notnull()

Int  Float  Complex
0   True   True    False
1   True   True     True
2   True   True    False
3  False   True     True
4   True   True     True
5   True  False    False

In [78]:
Df.notna()

Int  Float  Complex
0   True   True    False
1   True   True     True
2   True   True    False
3  False   True     True
4   True   True     True
5   True  False    False

In [79]:
Fill = np.nansum(Df['Int']).astype(float)
Fill

170.0

In [80]:
Fill_Missing_Value = Df.fillna(Fill,axis=1)
Fill_Missing_Value

Int  Float               Complex
0   10.0   20.5  170.000000+0.000000j
1   20.0   10.5    3.000000+2.000000j
2   30.0    5.5  170.000000+0.000000j
3  170.0    2.5   2.000000+23.000000j
4   50.0    6.5    2.000000+5.000000j
5   60.0  170.0  170.000000+0.000000j

In [81]:
for i in Df.columns:
    fill = np.nanmean(Df[i])
    Df[i].replace(np.nan,fill,inplace=True)
print(Df)

    Int  Float              Complex
0  10.0   20.5  2.333333+10.000000j
1  20.0   10.5   3.000000+2.000000j
2  30.0    5.5  2.333333+10.000000j
3  34.0    2.5  2.000000+23.000000j
4  50.0    6.5   2.000000+5.000000j
5  60.0    9.1  2.333333+10.000000j


In [82]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [83]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [84]:
data.fillna(method='ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [85]:
data.fillna(method='bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [86]:
df

A    B  C   D
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  9 NaN

In [87]:
df.fillna(method='ffill', axis=1)

A    B    C    D
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  9.0  9.0

In [88]:
df.fillna(method='bfill', axis=1)

A    B    C   D
0  1.0  2.0  2.0 NaN
1  2.0  3.0  5.0 NaN
2  4.0  4.0  9.0 NaN